// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using esbas_internship_backendproject;
using System.Xml;

#nullable disable

namespace esbas_internship_backendproject.Migrations
{
    [DbContext(typeof(EsbasDbContext))]
    [Migration("20240711115527_AddStatusColumn")]
    partial class AddStatusColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("esbas_internship_backendproject.Entities.Events", b =>
            {
                b.Property<int>("EventID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"), 1L, 1);

                b.Property<DateTime>("EventDateTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Type")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Location")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Status")
                    .HasColumnType("BIT");

                b.Property<bool>("EventStatus")
                    .HasColumnType("BIT");

                b.HasKey("EventID");

                b.ToTable("Events", (string)null);
            });

            modelBuilder.Entity("esbas_internship_backendproject.Entities.Events_Users", b =>
            {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                b.Property<int>("EventID")
                    .HasColumnType("int");

                b.Property<UniqueId>("CardID")
                    .HasColumnType("int");

                b.Property<bool>("Status")
                    .HasColumnType("BIT");

                b.HasKey("ID");

                b.ToTable("Events_Users", (string)null);
            });

            modelBuilder.Entity("esbas_internship_backendproject.Entities.Users", b =>
            {
                b.Property<int>("UserID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                b.Property<UniqueId>("CardID")
                  .HasColumnType("int");

                b.Property<string>("Department")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Gender")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("IsOfficeEmployee")
                    .HasColumnType("bit");

                b.Property<bool>("Status")
                    .HasColumnType("BIT");

                b.HasKey("UserID");

                b.ToTable("Users", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
